export enum CallStatus {
    RINGING = 'RINGING',
    CONNECTING = 'CONNECTING',
    ACTIVE = 'ACTIVE',
    RECONNECTING = 'RECONNECTING',
    ENDED = 'ENDED',
    MISSED = 'MISSED',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
    DECLINED = 'DECLINED',
    TIMEOUT = 'TIMEOUT',
}

export enum CallEndReason {
    MISSED = 'MISSED',
    DECLINED = 'DECLINED',
    CANCELLED = 'CANCELLED',
    FAILED = 'FAILED',
    DISCONNECTED = 'DISCONNECTED',
    REMOTE_LEFT = 'REMOTE_LEFT',
    ENDED = 'ENDED',
    TIMEOUT = 'TIMEOUT',
    ACCEPTED_ELSEWHERE = 'ACCEPTED_ELSEWHERE',
}
