export enum ErrorMessage {
    LOGIN_FAILED = 'Login failed, please check your credentials',
    EMAIL_CONFLICT_ERROR = 'User already exists.',
    USER_NOT_FOUND = 'User not found.',
    UNAUTHORIZED_ACCESS = 'Unauthorized access, please login',
    INVALID_TYPE = 'Invalid type found.',
    INVALID_OTP = 'Invalid OTP. Please try again.',
    OTP_EXPIRED = 'OTP expired. Please try again.',
    DOCUMENT_NOT_FOUND = 'Document not found',

    PROVIDER_NOT_FOUND = 'Provider not found',
    SERVICE_NOT_FOUND = 'Service not found',
    SUBSCRIPTION_NOT_FOUND = 'Subscription not found',
    PLAN_NOT_FOUND = 'Plan not found',
    PROVIDER_NOT_FOUND_WITH_ID = 'Provider not found with ID: ',
    CUSTOMER_NOT_FOUND_WITH_ID = 'Customer not found with ID: ',
    SERVICE_NOT_FOUND_WITH_ID = 'Service not found with ID: ',
    INVALID_INPUT = 'Invalid input data',
    MISSING_FIELDS = 'Required fields are missing',
    FILE_UPLOAD_FAILED = 'File upload failed',
    INVALID_CREDENTIALS = 'Invalid email or password',
    MUST_BE_STRING = 'must be a string',
    SHOULD_NOT_BE_EMPTY = 'should not be empty',
    FORBIDDEN_ACTION = 'You are not allowed to perform this action',
    USER_BLOCKED = 'You are blocked by the admin.',
    INTERNAL_SERVER_ERROR = 'An unexpected error occurred. Please try again later',
    DOCUMENT_CREATION_ERROR = 'Error creating document',
    DOCUMENT_ALREADY_EXISTS = 'Already exists',
    SOCKET_CONNECTION_REJECTED = 'Socket connection rejected: ',
    NO_TOKEN_FOUND = 'No token provided.',
    INVALID_REFRESH_TOKEN = 'Invalid or expired refresh token.',
    TOKEN_VERIFICATION_FAILED = 'Token verification failed.',
    UPLOAD_FAILED = 'Failed to upload an image.',
    SLOT_RESERVATION_FAILED = 'Slot already reserved. Please select another.',
    PAYMENT_IN_PROGRESS = 'Payment already in progress.',
    PAYMENT_VERIFICATION_FAILED = 'Payment verification failed.',
    BOOKING_ALREADY_CANCELLED = 'Booking is already cancelled.'
}

export enum ErrorCodes {
    MONGO_DUPLICATE_KEY = 'MONGO_DUPLICATE_KEY',
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    PAYMENT_IN_PROGRESS = 'PAYMENT_IN_PROGRESS',
    PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    DATABASE_OPERATION_FAILED = 'DATABASE_OPERATION_FAILED',
    BAD_REQUEST = 'BAD_REQUEST',
    CONFLICT = 'CONFLICT',
    NOT_FOUND = 'NOT_FOUND',
    NO_ACTIVE_SUBSCRIPTION = 'NO_ACTIVE_SUBSCRIPTION',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    PAYMENT_METHOD_DECLINED = 'PAYMENT_METHOD_DECLINED',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
    OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
    FILE_TOO_LARGE = 'FILE_TOO_LARGE',
    UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
}
